version: '3'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql-standalone
    environment:
      MYSQL_DATABASE: dockerservice
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  web:
    image: user-mysql
    restart: always
    depends_on:
     - db
    ports:
     - 8080:8080

  frontend:
   image: angular-image
   depends_on:
    - web
   ports:
    - 4200:4200


